language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS=""
    - TMPDIR=/tmp
    - USE_XDEBUG=false
    - COMPOSER_DISCARD_CHANGES=1

stages:
  - test
  - phpstan analysis
  - test with coverage

branches:
  only:
    master

install:
  - phpenv rehash
  - travis_retry composer update --no-interaction --prefer-stable $COMPOSER_ARGS

services:
  - memcached

before_script:
  - if [[ "$USE_XDEBUG" == false ]]; then phpenv config-rm xdebug.ini || return 0; fi
  - phpenv config-add tests/travis.ini

  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres

  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != 7* ]]; then phpenv config-add tests/config.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" == 7* ]]; then phpenv config-add tests/php7_config.ini; fi

  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
  - cd tests/
  - php runalltests.php

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  include:
    - php: 7.1
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.1
    - php: 7.2
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.2
    - php: 7.3
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.3
    - php: 7.4snapshot
      env: COMPOSER_ARGS="--ignore-platform-reqs --prefer-lowest"
    - php: 7.4snapshot
      env: COMPOSER_ARGS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_ARGS="--ignore-platform-reqs --prefer-lowest"
    - php: nightly
      env: COMPOSER_ARGS="--ignore-platform-reqs"

    - stage: phpstan analysis
      php: 7.2
      env: TMPDIR=/tmp USE_XDEBUG=false
      script:
        - ./bin/phpstan analyse -l 4 --autoload-file=vendor/autoload.php --memory-limit=1024M -c phpstan.neon ./library

    - stage: test with coverage
      php: 7.2
      env: COMPOSER_ARGS="" TMPDIR=/tmp USE_XDEBUG=true
      script:
        - cd tests/
        - php runalltests.php --coverage
      after_success:
        - cd ..
        - ./bin/phpcov merge ./build/coverage --clover=./build/coverage/clover.xml
        - bash <(curl -s https://codecov.io/bash) -f ./build/coverage/clover.xml
